// 카메라 MVP용 시연 데이터입니다.
// 확인하지 못한 값은 0이 아니라 null로 유지해 추천 결과까지 unknown을 전파합니다.

export const CAMERA_BODIES = [
  {
    id: "sony-a7-iv",
    name: "소니 A7 IV",
    brand: "Sony",
    series: "α7",
    model: "A7 IV",
    aliases: ["sony a7 iv", "sony a7iv", "소니 a7 iv", "a74", "a7m4"],
    mount: "Sony E",
    sensor: { format: "풀프레임", megapixels: 33, generation: "Exmor R BSI CMOS" },
    weight: 658,
    dimensions: [131.3, 96.4, 79.8],
    autofocus: { aiUnit: false, subjects: ["사람", "동물", "조류"], description: "실시간 추적 및 사람·동물·조류 인식" },
    video: { max: "4K 60p", bitDepth: 10, log: true, cropAtMax: true },
    batteryShots: 580,
    newPrice: 319,
    usedPrice: 240,
    useTags: ["여행 · 일상", "인물", "풍경", "가족 · 반려동물", "브이로그 · 영상"],
    photoScore: 4,
    videoScore: 4,
    portabilityScore: 2,
  },
  {
    id: "sony-a7c-ii",
    name: "소니 A7C II",
    brand: "Sony",
    series: "α7C",
    model: "A7C II",
    aliases: ["sony a7c ii", "sony a7c2", "소니 a7c ii", "소니 a7c2", "a7c2", "a7cm2"],
    mount: "Sony E",
    sensor: { format: "풀프레임", megapixels: 33, generation: "Exmor R BSI CMOS" },
    weight: 514,
    dimensions: [124, 71.1, 63.4],
    autofocus: { aiUnit: true, subjects: ["사람", "동물", "조류", "곤충", "자동차·기차", "비행기"], description: "전용 AI 처리 장치 기반 피사체 인식" },
    video: { max: "4K 60p", bitDepth: 10, log: true, cropAtMax: true },
    batteryShots: 560,
    newPrice: 269,
    usedPrice: 210,
    useTags: ["여행 · 일상", "인물", "풍경", "가족 · 반려동물", "브이로그 · 영상"],
    photoScore: 4,
    videoScore: 4,
    portabilityScore: 5,
  },
  {
    id: "canon-r6-ii",
    name: "캐논 EOS R6 Mark II",
    brand: "Canon",
    series: "EOS R6",
    model: "EOS R6 Mark II",
    aliases: ["canon r6 ii", "canon r6 mark ii", "캐논 r6 ii", "r6m2", "r62"],
    mount: "Canon RF",
    sensor: { format: "풀프레임", megapixels: 24.2, generation: null },
    weight: 670,
    dimensions: null,
    autofocus: null,
    video: null,
    batteryShots: null,
    newPrice: 299,
    usedPrice: 220,
    useTags: ["인물", "가족 · 반려동물", "스포츠 · 동물", "브이로그 · 영상"],
    photoScore: 4,
    videoScore: null,
    portabilityScore: 2,
  },
  {
    id: "nikon-z6-iii",
    name: "니콘 Z6 III",
    brand: "Nikon",
    series: "Z6",
    model: "Z6 III",
    aliases: ["nikon z6 iii", "니콘 z6 iii", "z63", "z6iii"],
    mount: "Nikon Z",
    sensor: { format: "풀프레임", megapixels: 24.5, generation: "부분 적층 CMOS" },
    weight: 670,
    dimensions: [138.5, 101.5, 74],
    autofocus: null,
    video: { max: "6K 60p RAW", bitDepth: null, log: true, cropAtMax: null },
    batteryShots: null,
    newPrice: 319,
    usedPrice: 280,
    useTags: ["인물", "풍경", "스포츠 · 동물", "브이로그 · 영상"],
    photoScore: 4,
    videoScore: 5,
    portabilityScore: 2,
  },
  {
    id: "fujifilm-x-t5",
    name: "후지필름 X-T5",
    brand: "Fujifilm",
    series: "X-T",
    model: "X-T5",
    aliases: ["fujifilm x-t5", "후지필름 x-t5", "후지 xt5", "xt5"],
    mount: "Fujifilm X",
    sensor: { format: "APS-C", megapixels: 40.2, generation: "X-Trans CMOS 5 HR" },
    weight: 557,
    dimensions: [129.5, 91, 63.8],
    autofocus: null,
    video: { max: "6.2K 30p", bitDepth: 10, log: true, cropAtMax: null },
    batteryShots: 580,
    newPrice: 249,
    usedPrice: 195,
    useTags: ["여행 · 일상", "인물", "풍경"],
    photoScore: 5,
    videoScore: 3,
    portabilityScore: 3,
  },
  {
    id: "fujifilm-x-e4",
    name: "후지필름 X-E4",
    brand: "Fujifilm",
    series: "X-E",
    model: "X-E4",
    aliases: ["fujifilm x-e4", "후지필름 x-e4", "후지 xe4", "xe4"],
    mount: "Fujifilm X",
    sensor: { format: "APS-C", megapixels: 26.1, generation: null },
    weight: 364,
    dimensions: null,
    autofocus: null,
    video: null,
    batteryShots: 460,
    newPrice: 125,
    usedPrice: 150,
    useTags: ["여행 · 일상", "인물", "풍경"],
    photoScore: 4,
    videoScore: null,
    portabilityScore: 5,
  },
  {
    id: "panasonic-g9-ii",
    name: "파나소닉 루믹스 G9 II",
    brand: "Panasonic",
    series: "LUMIX G",
    model: "LUMIX G9 II",
    aliases: ["panasonic g9 ii", "파나소닉 g9 ii", "루믹스 g9 ii", "g92"],
    mount: "Micro Four Thirds",
    sensor: { format: "마이크로포서드", megapixels: null, generation: null },
    weight: 658,
    dimensions: null,
    autofocus: null,
    video: null,
    batteryShots: null,
    newPrice: 239,
    usedPrice: 180,
    useTags: ["풍경", "스포츠 · 동물", "브이로그 · 영상"],
    photoScore: 4,
    videoScore: null,
    portabilityScore: 2,
  },
];

export const CAMERA_LENSES = [
  { id: "sony-fe-24-70-gm2", name: "Sony FE 24-70mm F2.8 GM II", brand: "Sony", mount: "Sony E", type: "zoom", focal: { min: 24, max: 70 }, aperture: { wide: 2.8, tele: 2.8 }, weight: 695, stabilization: false, newPrice: 289, usedPrice: 220, roles: ["여행 · 일상", "인물", "풍경"], photoScore: 5, videoScore: 4, portabilityScore: 1, dataStatus: "known" },
  { id: "sony-fe-70-200-gm2", name: "Sony FE 70-200mm F2.8 GM II", brand: "Sony", mount: "Sony E", type: "zoom", focal: { min: 70, max: 200 }, aperture: { wide: 2.8, tele: 2.8 }, weight: 1045, stabilization: true, newPrice: 339, usedPrice: 260, roles: ["인물", "스포츠 · 동물"], photoScore: 5, videoScore: 4, portabilityScore: 1, dataStatus: "known" },
  { id: "sony-fe-40-g", name: "Sony FE 40mm F2.5 G", brand: "Sony", mount: "Sony E", type: "prime", focal: { min: 40, max: 40 }, aperture: { wide: 2.5, tele: 2.5 }, weight: 173, stabilization: false, newPrice: 72, usedPrice: 52, roles: ["여행 · 일상", "인물"], photoScore: 4, videoScore: 3, portabilityScore: 5, dataStatus: "known" },
  { id: "sony-fe-28-60", name: "Sony FE 28-60mm F4-5.6", brand: "Sony", mount: "Sony E", type: "zoom", focal: { min: 28, max: 60 }, aperture: { wide: 4, tele: 5.6 }, weight: 167, stabilization: false, newPrice: 35, usedPrice: 22, roles: ["여행 · 일상", "풍경"], photoScore: 3, videoScore: 3, portabilityScore: 5, dataStatus: "known" },
  { id: "fuji-xf-18-55", name: "Fujifilm XF 18-55mm F2.8-4", brand: "Fujifilm", mount: "Fujifilm X", type: "zoom", focal: { min: 18, max: 55 }, aperture: { wide: 2.8, tele: 4 }, weight: 310, stabilization: true, newPrice: 52, usedPrice: 38, roles: ["여행 · 일상", "인물", "풍경", "브이로그 · 영상"], photoScore: 4, videoScore: 4, portabilityScore: 4, dataStatus: "known" },
  { id: "fuji-xf-27", name: "Fujifilm XF 27mm F2.8 R WR", brand: "Fujifilm", mount: "Fujifilm X", type: "prime", focal: { min: 27, max: 27 }, aperture: { wide: 2.8, tele: 2.8 }, weight: 84, stabilization: false, newPrice: 58, usedPrice: 43, roles: ["여행 · 일상"], photoScore: 4, videoScore: 2, portabilityScore: 5, dataStatus: "known" },
  { id: "canon-rf-24-50", name: "Canon RF 24-50mm F4.5-6.3", brand: "Canon", mount: "Canon RF", type: "zoom", focal: { min: 24, max: 50 }, aperture: { wide: 4.5, tele: 6.3 }, weight: 210, stabilization: false, newPrice: 35, usedPrice: 23, roles: ["여행 · 일상", "풍경"], photoScore: 3, videoScore: 3, portabilityScore: 5, dataStatus: "known" },
  { id: "canon-rf-24-105-f4", name: "Canon RF 24-105mm F4 L IS USM", brand: "Canon", mount: "Canon RF", type: "zoom", focal: { min: 24, max: 105 }, aperture: { wide: 4, tele: 4 }, weight: 700, stabilization: true, newPrice: 169, usedPrice: 115, roles: ["여행 · 일상", "인물", "풍경"], photoScore: 4, videoScore: 4, portabilityScore: 2, dataStatus: "known" },
  { id: "nikon-z-24-70-f4", name: "Nikon Z 24-70mm F4 S", brand: "Nikon", mount: "Nikon Z", type: "zoom", focal: { min: 24, max: 70 }, aperture: { wide: 4, tele: 4 }, weight: 500, stabilization: false, newPrice: 89, usedPrice: 55, roles: ["여행 · 일상", "인물", "풍경", "브이로그 · 영상"], photoScore: 4, videoScore: 4, portabilityScore: 3, dataStatus: "known" },
  { id: "nikon-z-40-f2", name: "Nikon Z 40mm F2", brand: "Nikon", mount: "Nikon Z", type: "prime", focal: { min: 40, max: 40 }, aperture: { wide: 2, tele: 2 }, weight: 170, stabilization: false, newPrice: 35, usedPrice: 24, roles: ["여행 · 일상", "인물"], photoScore: 4, videoScore: 3, portabilityScore: 5, dataStatus: "known" },
  { id: "mft-12-60", name: "Panasonic Leica 12-60mm F2.8-4", brand: "Panasonic", mount: "Micro Four Thirds", type: "zoom", focal: { min: 12, max: 60 }, aperture: { wide: 2.8, tele: 4 }, weight: 320, stabilization: true, newPrice: 99, usedPrice: 62, roles: ["여행 · 일상", "인물", "풍경", "브이로그 · 영상"], photoScore: 4, videoScore: 4, portabilityScore: 4, dataStatus: "known" },
];

export const BODY_BY_NAME = Object.fromEntries(CAMERA_BODIES.map((body) => [body.name, body]));
export const BODY_BY_ID = Object.fromEntries(CAMERA_BODIES.map((body) => [body.id, body]));
export const LENS_BY_NAME = Object.fromEntries(CAMERA_LENSES.map((lens) => [lens.name, lens]));

export function normalizeCameraSearch(value) {
  return String(value || "")
    .toLowerCase()
    .replaceAll("α", "a")
    .replaceAll("mark", "m")
    .replace(/[^a-z0-9가-힣]/g, "");
}

export function searchCameraBodies(query) {
  const needle = normalizeCameraSearch(query);
  if (!needle) return [];
  return CAMERA_BODIES.filter((body) => [body.name, body.brand, body.series, body.model, ...(body.aliases || [])]
    .some((value) => normalizeCameraSearch(value).includes(needle)));
}

export function createUnknownBody(name, brand = "기타", series = "기타") {
  return {
    id: `unknown-${name}`,
    name,
    brand,
    series,
    model: name,
    aliases: [],
    mount: null,
    sensor: null,
    weight: null,
    dimensions: null,
    autofocus: null,
    video: null,
    batteryShots: null,
    newPrice: null,
    usedPrice: null,
    useTags: [],
    photoScore: null,
    videoScore: null,
    portabilityScore: null,
    dataStatus: "unknown",
  };
}

export function createUnknownLens(name, mount = null) {
  return {
    id: `unknown-${name}`,
    name,
    brand: null,
    mount,
    type: null,
    focal: null,
    aperture: null,
    weight: null,
    stabilization: null,
    newPrice: null,
    usedPrice: null,
    roles: [],
    photoScore: null,
    videoScore: null,
    portabilityScore: null,
    dataStatus: "unknown",
  };
}
